name: Generate Sitemap from Rendered Page

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # every day at 3am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install playwright beautifulsoup4
          playwright install chromium

      - name: Run Sitemap Generator
        run: python scripts/generate_sitemap.py

      - name: Commit and Push sitemap.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap.xml" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
